// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/cryptography/EIP712.sol";
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";

/**
 * @title TripToken ($TRIP)
 * @dev ERC-20 token for Tripchain eco-mobility rewards.
 * Supports EIP-712 cryptographic voucher minting authorized by Tripchain Oracle.
 */
contract TripToken is ERC20, ERC20Burnable, Ownable, EIP712 {
    using ECDSA for bytes32;

    // Authorized backend validator / oracle address that signs claim vouchers
    address public validatorSigner;

    // Typehash for EIP-712 structured data signing
    bytes32 public constant CLAIM_TYPEHASH = keccak256(
        "ClaimVoucher(address recipient,uint256 amount,uint256 nonce,uint256 deadline)"
    );

    // Track used nonces per recipient to prevent replay attacks
    mapping(address => mapping(uint256 => bool)) public usedNonces;

    // Event emitted when tokens are claimed via voucher
    event RewardClaimed(address indexed recipient, uint256 amount, uint256 nonce);
    
    // Event emitted when tokens are burned specifically for carbon offset
    event TokensBurnedForOffset(address indexed user, uint256 amount, string memo, uint256 timestamp);

    // Event emitted when validator signer address is updated
    event ValidatorSignerUpdated(address indexed previousSigner, address indexed newSigner);

    constructor(
        address initialOwner,
        address _validatorSigner
    ) ERC20("Tripchain Token", "TRIP") Ownable(initialOwner) EIP712("Tripchain", "1.0") {
        require(_validatorSigner != address(0), "Invalid validator signer");
        validatorSigner = _validatorSigner;

        // Initial ecosystem reserve: 1,000,000 $TRIP to initial owner
        _mint(initialOwner, 1_000_000 * 10 ** decimals());
    }

    /**
     * @notice Set or rotate the authorized validator signer address.
     */
    function setValidatorSigner(address _newSigner) external onlyOwner {
        require(_newSigner != address(0), "Invalid signer address");
        emit ValidatorSignerUpdated(validatorSigner, _newSigner);
        validatorSigner = _newSigner;
    }

    /**
     * @notice Claim $TRIP reward tokens using an EIP-712 signature from Tripchain backend.
     * @param amount Amount of tokens to mint (with 18 decimals)
     * @param nonce Unique claim nonce to prevent replay
     * @param deadline Expiration timestamp (seconds since unix epoch)
     * @param signature Cryptographic signature generated by validatorSigner
     */
    function claimRewardWithSignature(
        uint256 amount,
        uint256 nonce,
        uint256 deadline,
        bytes calldata signature
    ) external {
        require(block.timestamp <= deadline, "TripToken: Claim voucher expired");
        require(!usedNonces[msg.sender][nonce], "TripToken: Voucher already claimed");
        require(amount > 0, "TripToken: Amount must be greater than zero");

        // Hash the typed struct data
        bytes32 structHash = keccak256(
            abi.encode(CLAIM_TYPEHASH, msg.sender, amount, nonce, deadline)
        );

        // Compute EIP-712 digest
        bytes32 digest = _hashTypedDataV4(structHash);

        // Recover signer from signature
        address signer = digest.recover(signature);
        require(signer == validatorSigner, "TripToken: Invalid validator signature");

        // Mark nonce as used
        usedNonces[msg.sender][nonce] = true;

        // Mint reward tokens
        _mint(msg.sender, amount);

        emit RewardClaimed(msg.sender, amount, nonce);
    }

    /**
     * @notice Burn tokens directly with an attached carbon offset memo.
     */
    function burnForOffset(uint256 amount, string calldata memo) external {
        burn(amount);
        emit TokensBurnedForOffset(msg.sender, amount, memo, block.timestamp);
    }

    /**
     * @notice Standard admin mint for faucet, testnet liquidity, or community grants.
     */
    function mint(address to, uint256 amount) external onlyOwner {
        _mint(to, amount);
    }
}
