-- AlterTable
ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "routeType" TEXT DEFAULT 'fastest';
ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "co2Saved" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "points" INTEGER DEFAULT 10;
