apiVersion: v1
kind: Secret
metadata:
  name: tripchain-secrets
type: Opaque
stringData:
  # Base64 encoded values are not needed for stringData
  # Backend variables
  DATABASE_URL: "postgresql://neondb_owner:npg_bi62KtRBJHdX@ep-autumn-violet-axsuxlkn-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require&pgbouncer=true&connect_timeout=15"
  DIRECT_URL: "postgresql://neondb_owner:npg_bi62KtRBJHdX@ep-autumn-violet-axsuxlkn.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require"
  PORT: "5000"
  JWT_SECRET: "tripchain_super_secret"
